import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header } from '../_components/shares'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}
export async function generateStaticParams() {
  return [{ lang: 'en-US' }, { lang: 'de' }]
}
export default function RootLayout({ children, params }: { children: React.ReactNode; params: any }) {
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
